#!/usr/bin/env bash


name="isaac"

update(){
    set -e
    echo "Updating $name..."

    pushd "$ARENA_DIR" > /dev/null || return 1
        git submodule update --init arena_isaac
    popd > /dev/null || return 1

    arena_docker_compose build isaac
    arena_docker_compose up -d --remove-orphans --no-start isaac
}

uninstall(){
    arena_docker_compose rm -fs isaac || true
    pushd "$ARENA_DIR" > /dev/null || return 1
        git submodule deinit -f arena_isaac
    popd > /dev/null || return 1
    arena registry remove "$name"
}

source_fn(){
    if [[ ! "$ARENA_MODELS_FORMATS" =~ usd ]]; then
        export ARENA_MODELS_FORMATS="${ARENA_MODELS_FORMATS},usdz,usd,usda,usdc"
    fi
}

launch(){
    arena_docker_compose up -d --remove-orphans isaac
    trap 'arena_docker_compose stop isaac || true' EXIT INT TERM
    arena_docker_compose exec -T isaac bash -c \
        'source /opt/arena_ws/install/local_setup.bash && python3-arena /opt/arena_ws/build/arena_isaac/arena_isaac/run_isaacsim.py "$@"' \
        -- "$@" || return $?
}

# === MAIN SCRIPT ===
help(){
    echo "Usage: $name <update|uninstall|source|launch|exec>"
}
if [ $# -lt 1 ]; then
    help
    exit 1
fi
case "$1" in
    update)
        update
        exit $?
    ;;
    uninstall)
        uninstall
        exit $?
    ;;
    source)
        source_fn
        return $?
    ;;
    launch)
        shift
        launch "$@"
        exit $?
    ;;
    exec)
        shift
        arena_docker_compose exec isaac "$@"
        exit $?
    ;;
    *)
        help
        exit 1
    ;;
esac
