#!/bin/bash -i

install(){
    echo 'Enabled optional planners'
}

uninstall(){
    #TODO
    echo not implemented
}

# === MAIN SCRIPT ===
help(){
    echo "Usage: planners.sh <install|uninstall>"
}
if [ $# -ne 1 ]; then
    help
    exit 1
fi
case "$1" in
    install)
        install
        exit $?
    ;;
    update)
        exit 0
    ;;
    uninstall)
        uninstall
        exit $?
    ;;
    source)
        return 0
    ;;
    *)
        help
        exit 1
    ;;
esac