ARG ROS_DISTRO=jazzy
FROM osrf/ros:${ROS_DISTRO}-desktop AS base


RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    python-is-python3 \
    python3-pip \
    pipx \
    python3-colcon-common-extensions \
    python3-rosdep \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

RUN pipx install git+https://github.com/voshch/vcstool.git

WORKDIR /opt/arena_ws

# install python deps
FROM base AS python_deps
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /build
COPY src/Arena/pyproject.toml uv.lock* ./

RUN uv venv /opt/venv


# merge
FROM base AS final
ARG username=arena
ARG group=arena
ARG uid=1000
ARG gid=1000

COPY --from=python_deps --chown=${uid}:${gid} /opt/venv /opt/venv
COPY --from=python_deps /usr/local/bin/uv /usr/local/bin/uv


RUN (getent passwd ${uid} && userdel -rf $(getent passwd ${uid} | cut -d: -f1)) 2>/dev/null || true && \
    (getent group ${gid} && groupdel -f $(getent group ${gid} | cut -d: -f1)) 2>/dev/null || true && \
    groupadd -g ${gid} ${group} && \
    useradd -m -u ${uid} -g ${gid} -s /bin/bash ${username} && \
    passwd -d ${username} && \
    usermod -aG docker ${username} && \
    usermod -aG sudo ${username}

WORKDIR /opt/arena_ws

RUN mkdir -p build
RUN mkdir -p install
RUN mkdir -p log
RUN chown -R ${uid}:${gid} /opt/arena_ws

COPY src/Arena/_meta/docker/entrypoint.sh /entrypoint.sh
COPY --chown=${uid}:${gid} src/Arena/_meta/docker/source.container source.container
RUN chmod +x /entrypoint.sh
USER ${username}
ENTRYPOINT ["/entrypoint.sh"]