#!/usr/bin/env bash

ARENA_WS_DIR="${ARENA_WS_DIR:-$(pwd)}"

export ARENA_WS_DIR
export ARENA_DIR="$ARENA_WS_DIR/src/Arena"
export ARENA_ROS_DISTRO=jazzy

mkdir -p "$ARENA_DIR/.venv"
mkdir -p "$ARENA_WS_DIR/build"
mkdir -p "$ARENA_WS_DIR/install"
mkdir -p "$ARENA_WS_DIR/log"

export ARENA_IMAGE="arena:dev"
export HOST_UID=$(id -u)
export PROJECT_NAME="arena"

if [ ! -f "$ARENA_WS_DIR/.env" ] ; then
    touch "$ARENA_WS_DIR/.env"
fi

xhost +local:docker

docker compose \
    -f "$ARENA_DIR/_meta/docker/docker-compose.yaml" \
    --project-directory "$ARENA_WS_DIR" \
    --project-name "$PROJECT_NAME" \
    up --remove-orphans --no-start \
    arena

CONTAINER_ID=$(docker compose \
    -f "$ARENA_DIR/_meta/docker/docker-compose.yaml" \
    --project-directory "$ARENA_WS_DIR" \
    --project-name "$PROJECT_NAME" \
    ps -q -a arena \
    | tail -n 1)

docker start -i "$CONTAINER_ID"