#!/usr/bin/env bash

ARENA_WS_DIR="${ARENA_WS_DIR:-$(pwd)}"

export ARENA_WS_DIR
export ARENA_DIR="$ARENA_WS_DIR/src/Arena"

mkdir -p "$ARENA_DIR/.venv"
mkdir -p "$ARENA_WS_DIR/build"
mkdir -p "$ARENA_WS_DIR/install"
mkdir -p "$ARENA_WS_DIR/log"

ARENA_IMAGE="arena:dev"
CONTAINER_PID_FILE="$ARENA_WS_DIR/.container.pid"

HOST_UID=$(id -u)
HOST_GID=$(id -g)

if [[ -f "$CONTAINER_PID_FILE" ]]; then
    CONTAINER_ID="$(cat "$CONTAINER_PID_FILE")"
    if docker inspect "$CONTAINER_ID" > /dev/null 2>&1; then
        docker start "$CONTAINER_ID" > /dev/null
        docker container exec -it "$CONTAINER_ID" /entrypoint.sh bash
        # docker stop "$CONTAINER_ID"
        return $?
    else
        rm -f "$CONTAINER_PID_FILE"
    fi
fi

docker run \
    -it \
    --cidfile "$CONTAINER_PID_FILE" \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -w /opt/arena_ws \
    --network host \
    -v "$ARENA_WS_DIR/src":/opt/arena_ws/src \
    -v "$ARENA_WS_DIR/build":/opt/arena_ws/build \
    -v "$ARENA_WS_DIR/install":/opt/arena_ws/install \
    -v "$ARENA_WS_DIR/log":/opt/arena_ws/log \
    -e "ARENA_IMAGE=${ARENA_IMAGE}" \
    --user "${HOST_UID}:${HOST_GID}" \
    "$ARENA_IMAGE" \
    bash