#!/usr/bin/env bash


docker_update(){
    arena_docker_compose \
        build \
        arena
}

docker_commit(){
    CONTAINER_ID=$(arena_docker_compose \
        ps -q -a arena \
        | tail -n 1)
    echo "committing container to image $ARENA_IMAGE..."
    sudo ${docker_env[*]} docker commit "$CONTAINER_ID" "$ARENA_IMAGE"
    echo "done"
}

# === MAIN SCRIPT ===
help(){
    echo "Usage: arena feature docker <update|commit>"
}

if [ $# -ne 1 ]; then
    help
    exit 1
fi
case "$1" in
    update)
        docker_update
    ;;
    commit)
        docker_commit
    ;;
    *)
        help
        exit 1
    ;;
esac
