#!/usr/bin/env python

import os
import sys

from arena_simulation_setup.staging import stage

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(f'usage: {os.path.basename(__file__)} <install_dir>')
        sys.exit(1)
    stage(sys.argv[1])
