#!/usr/bin/env bash

name="gazebo"

source_fn(){
  export USD_PATH="$ARENA_WS_DIR/tools/OpenUSD/install"
  export PATH="$USD_PATH/bin:$PATH"
  export LD_LIBRARY_PATH="$USD_PATH/lib:$LD_LIBRARY_PATH"
  export CMAKE_PREFIX_PATH="$USD_PATH:$CMAKE_PREFIX_PATH"
  if [[ ! "$ARENA_MODELS_FORMATS" =~ sdf ]]; then
    export ARENA_MODELS_FORMATS="${ARENA_MODELS_FORMATS},sdf"
  fi
}

update(){
  set -e
  source_fn
  cd "$ARENA_WS_DIR"

  sudo apt-get update
  sudo apt-get install -y \
    ros-$ARENA_ROS_DISTRO-ros-gz-sim \
    ros-$ARENA_ROS_DISTRO-ros-gz-bridge \
    ros-$ARENA_ROS_DISTRO-ros-gz-image

  echo "Gazebo ${GAZEBO_VERSION}, ros_gz, sdformat_urdf installed successfully!"

  if [ ! -d tools/OpenUSD ]; then
    echo "Installing OpenUSD"
    mkdir -p tools
    pushd tools > /dev/null || return 1
      git clone --depth 1 -b v24.08 https://github.com/PixarAnimationStudios/OpenUSD.git
      sudo apt-get install -y libpyside2-dev python3-opengl cmake libglu1-mesa-dev freeglut3-dev mesa-common-dev
      cd OpenUSD
      python3 build_scripts/build_usd.py --build-variant release --no-tests --no-examples --no-imaging --onetbb --no-tutorials --no-docs --no-python "$USD_PATH"
    popd > /dev/null || return 1
  fi

  if [ ! -d src/tools/gz-usd ]; then
    echo "Installing gz-usd"
    sudo apt-get install -y libgz-cmake4-dev libsdformat15-dev libgz-common6-dev
    mkdir -p src/tools
    pushd src/tools > /dev/null || return 1
      git clone -b main https://github.com/gazebosim/gz-usd
    popd > /dev/null || return 1
    BASE_PATHS=src/tools/gz-usd arena build
    echo "Successfully installed gz-usd"
  fi
}

uninstall(){
  arena registry remove "$name"
}


# === MAIN SCRIPT ===
help(){
  echo "Usage: $name <install|update|uninstall|source|launch>"
}
if [ $# -lt 1 ]; then
  help
  exit 1
fi
case "$1" in
  install)
    _feature_default_install "$name"
    exit $?
    ;;
  update)
    update
    exit $?
    ;;
  uninstall)
    uninstall
    # shellcheck disable=SC2317
    return $? 2>/dev/null || exit $?
    ;;
  source)
    source_fn
    return $?
    ;;
  launch)
    shift
    exec ros2 launch arena_bringup gazebo.launch.py "$@"
    ;;
  *)
    help
    exit 1
    ;;
esac
