#!/usr/bin/env bash

name="planners"

update(){
    return 0
}

uninstall(){
    arena registry remove "$name"
}

# === MAIN SCRIPT ===
help(){
    echo "Usage: $name <update|uninstall|source>"
}
if [ $# -lt 1 ]; then
    help
    exit 1
fi
case "$1" in
    update)
        update
        exit $?
    ;;
    uninstall)
        uninstall
        # shellcheck disable=SC2317
        return $? 2>/dev/null || exit $?
    ;;
    source)
        return 0
    ;;
    *)
        help
        exit 1
    ;;
esac
