#!/usr/bin/env bash

create_link(){
    local target=$1
    local link_name

    case $2 in
        /*) link_name="$2" ;;
        *) link_name="$ARENA_WS_DIR/$2" ;;
    esac

    if [ -e "$link_name" ] || [ -L "$link_name" ] ; then
        return 0
    else
        mkdir -p "$(dirname "$link_name")"
        echo "Creating link: $link_name -> $target"
        ln -rs "$target" "$link_name"
        return $?
    fi
}

create_link "$ARENA_DIR/_meta/tools/source" "arena"
create_link "$ARENA_DIR/_meta/tools/Arena.code-workspace" "ws-arena.code-workspace"
create_link "$ARENA_DIR/simulation_setup/assets" "$ARENA_ASSETS_DIR/_local"